version: '3'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
    - ./gitlab-runner/config:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    container_name: gitlab_runner
